language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  cleanup: false
  local_dir: docs/.vuepress/dist
  token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: docs